import { getValidId } from './query';

const lineCommentTemplate: { [lang: string]: (line: string) => string } = {
  text: (line) => line,
  bash: (line) => `# ${line}`,
  basic: (line) => `REM ${line}`,
  c: (line) => `// ${line}`,
  cpp: (line) => `// ${line}`,
  csharp: (line) => `// ${line}`,
  css: (line) => `/* ${line} */`,
  dart: (line) => `// ${line}`,
  diff: (line) => line,
  django: (line) => `<!-- ${line} -->`,
  docker: (line) => `# ${line}`,
  erlang: (line) => `% ${line}`,
  go: (line) => `// ${line}`,
  graphql: (line) => `# ${line}`,
  groovy: (line) => `// ${line}`,
  html: (line) => `<!-- ${line} -->`,
  http: (line) => line,
  java: (line) => `// ${line}`,
  javascript: (line) => `// ${line}`,
  json: (line) => `// ${line}`,
  jsx: (line) => `// ${line}`,
  kotlin: (line) => `// ${line}`,
  less: (line) => `/* ${line} */`,
  makefile: (line) => `# ${line}`,
  markdown: (line) => `; ${line}`,
  matlab: (line) => `% ${line}`,
  nginx: (line) => `# ${line}`,
  objectivec: (line) => `// ${line}`,
  pascal: (line) => `// ${line}`,
  perl: (line) => `# ${line}`,
  php: (line) => `// ${line}`,
  powershell: (line) => `# ${line}`,
  protobuf: (line) => `// ${line}`,
  python: (line) => `# ${line}`,
  r: (line) => `# ${line}`,
  ruby: (line) => `# ${line}`,
  rust: (line) => `// ${line}`,
  scala: (line) => `// ${line}`,
  shell: (line) => `# ${line}`,
  sql: (line) => `-- ${line}`,
  plsql: (line) => `-- ${line}`,
  swift: (line) => `// ${line}`,
  tsx: (line) => `// ${line}`,
  typescript: (line) => `// ${line}`,
  vbnet: (line) => `' ${line}`,
  velocity: (line) => `## ${line}`,
  xml: (line) => `<!-- ${line} -->`,
  yaml: (line) => `# ${line}`,
  latex: (line) => `% ${line}`,
  tcl: (line) => `# ${line}`,
  verilog: (line) => `// ${line}`,
  lua: (line) => `-- ${line}`,
};

export function comment(code: string, lang: string) {
  const langId = getValidId(lang);
  const tmpl = lineCommentTemplate[langId];
  return typeof tmpl === 'function' ? tmpl(code) : code;
}
